/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardClimaRouteImport } from './routes/dashboard.clima'
import { Route as DashboardConfiguracionRouteImport } from './routes/dashboard.configuracion'
import { Route as DashboardCultivosRouteImport } from './routes/dashboard.cultivos'
import { Route as DashboardHistorialRouteImport } from './routes/dashboard.historial'
import { Route as DashboardMonitoreoRouteImport } from './routes/dashboard.monitoreo'
import { Route as DashboardRiegoRouteImport } from './routes/dashboard.riego'
import { Route as DashboardSensoresRouteImport } from './routes/dashboard.sensores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClimaRoute = DashboardClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracionRoute = DashboardConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCultivosRoute = DashboardCultivosRouteImport.update({
  id: '/cultivos',
  path: '/cultivos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistorialRoute = DashboardHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoreoRoute = DashboardMonitoreoRouteImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRiegoRoute = DashboardRiegoRouteImport.update({
  id: '/riego',
  path: '/riego',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSensoresRoute = DashboardSensoresRouteImport.update({
  id: '/sensores',
  path: '/sensores',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/clima': typeof DashboardClimaRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/cultivos': typeof DashboardCultivosRoute
  '/dashboard/historial': typeof DashboardHistorialRoute
  '/dashboard/monitoreo': typeof DashboardMonitoreoRoute
  '/dashboard/riego': typeof DashboardRiegoRoute
  '/dashboard/sensores': typeof DashboardSensoresRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/clima': typeof DashboardClimaRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/cultivos': typeof DashboardCultivosRoute
  '/dashboard/historial': typeof DashboardHistorialRoute
  '/dashboard/monitoreo': typeof DashboardMonitoreoRoute
  '/dashboard/riego': typeof DashboardRiegoRoute
  '/dashboard/sensores': typeof DashboardSensoresRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/clima': typeof DashboardClimaRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/cultivos': typeof DashboardCultivosRoute
  '/dashboard/historial': typeof DashboardHistorialRoute
  '/dashboard/monitoreo': typeof DashboardMonitoreoRoute
  '/dashboard/riego': typeof DashboardRiegoRoute
  '/dashboard/sensores': typeof DashboardSensoresRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/clima'
    | '/dashboard/configuracion'
    | '/dashboard/cultivos'
    | '/dashboard/historial'
    | '/dashboard/monitoreo'
    | '/dashboard/riego'
    | '/dashboard/sensores'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/clima'
    | '/dashboard/configuracion'
    | '/dashboard/cultivos'
    | '/dashboard/historial'
    | '/dashboard/monitoreo'
    | '/dashboard/riego'
    | '/dashboard/sensores'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/clima'
    | '/dashboard/configuracion'
    | '/dashboard/cultivos'
    | '/dashboard/historial'
    | '/dashboard/monitoreo'
    | '/dashboard/riego'
    | '/dashboard/sensores'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clima': {
      id: '/dashboard/clima'
      path: '/clima'
      fullPath: '/dashboard/clima'
      preLoaderRoute: typeof DashboardClimaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracion': {
      id: '/dashboard/configuracion'
      path: '/configuracion'
      fullPath: '/dashboard/configuracion'
      preLoaderRoute: typeof DashboardConfiguracionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cultivos': {
      id: '/dashboard/cultivos'
      path: '/cultivos'
      fullPath: '/dashboard/cultivos'
      preLoaderRoute: typeof DashboardCultivosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/historial': {
      id: '/dashboard/historial'
      path: '/historial'
      fullPath: '/dashboard/historial'
      preLoaderRoute: typeof DashboardHistorialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoreo': {
      id: '/dashboard/monitoreo'
      path: '/monitoreo'
      fullPath: '/dashboard/monitoreo'
      preLoaderRoute: typeof DashboardMonitoreoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/riego': {
      id: '/dashboard/riego'
      path: '/riego'
      fullPath: '/dashboard/riego'
      preLoaderRoute: typeof DashboardRiegoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sensores': {
      id: '/dashboard/sensores'
      path: '/sensores'
      fullPath: '/dashboard/sensores'
      preLoaderRoute: typeof DashboardSensoresRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClimaRoute: typeof DashboardClimaRoute
  DashboardConfiguracionRoute: typeof DashboardConfiguracionRoute
  DashboardCultivosRoute: typeof DashboardCultivosRoute
  DashboardHistorialRoute: typeof DashboardHistorialRoute
  DashboardMonitoreoRoute: typeof DashboardMonitoreoRoute
  DashboardRiegoRoute: typeof DashboardRiegoRoute
  DashboardSensoresRoute: typeof DashboardSensoresRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClimaRoute: DashboardClimaRoute,
  DashboardConfiguracionRoute: DashboardConfiguracionRoute,
  DashboardCultivosRoute: DashboardCultivosRoute,
  DashboardHistorialRoute: DashboardHistorialRoute,
  DashboardMonitoreoRoute: DashboardMonitoreoRoute,
  DashboardRiegoRoute: DashboardRiegoRoute,
  DashboardSensoresRoute: DashboardSensoresRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
